### ISSUE TITLE
The plugin shouldn't wait 15 seconds when it's trying to catch up

### ISSUE THREAD

**Issue by iserko** [iserko/logstash-input-cloudflare#1]
When you haven't been running logstash you'd like the plugin to catch up as soon as possible, so we need to remove the 15 seconds wait time.

**Comment by eeroniemi** [comment]
You can always set parameter `poll_time` to 0 on input configuration. This disables the wait time.

**Comment by iserko** [comment]
@eeroniemi that would be fine, but you'd need to change it as soon as you caught up ... and then if it happened again, you'd need to detect it and trigger it again ... what I would suggest is to continue requesting against the API until you've caught up to about 10 minutes from now.
